TestPlatform/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TestingService.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

TestingService/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.forms import AuthenticationForm
from django.urls import path

from TestingService import views


urlpatterns = [
    path('', views.ListPolls.as_view(), name='ListPolls'),
    path('<int:pk>/', views.ListQuestions.as_view(), name='ListQuestions'),
    path('question/<int:pk>/', views.ListAnswers.as_view(), name='ListAnswers'),
    path('result/', views.ResultPollsStudent.as_view(), name='ResultForStudent'),
    path('registration/', views.registration_user, name='registration_user'),
    path('login/', views.LoginViewAnonUser.as_view(template_name='login.html', authentication_form=AuthenticationForm),
         name='LoginViewAnonUser'),
    path('studentpolls/', views.ListStudent.as_view(), name='ListStudent'),
    path('studentpolls/users/<int:pk>/', views.DetailStudentPollsResult.as_view(),
         name='DetailStudentPollsResult'),
    path('studentpolls/users/<int:pk_2>/poll/<int:pk_1>/', views.result_student_poll, name='result_student_poll'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TestingService/models.py
from django.conf import settings
from django.contrib.auth.models import User, AbstractUser
from django.db import models


# Create your models here.


class Poll(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Question(models.Model):
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    text = models.CharField(max_length=50)

    def __str__(self):
        return self.text


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=50)
    is_correct = models.BooleanField()

    def __str__(self):
        return self.answer_text


class MyUser(AbstractUser):
    is_teacher = models.BooleanField(default=True)

    def __str__(self):
        return self.username


class StudentAnswer(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    votes = models.IntegerField(default=0)
    created_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.answer.answer_text

TestingService/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm

from TestingService.models import MyUser


class RegistrationForm(UserCreationForm):
    is_teacher = forms.BooleanField(required=False)

    class Meta:
        model = MyUser
        fields = ('username', 'password1', 'password2', 'is_teacher', 'email')

TestingService/views.py
from django.contrib.auth import authenticate, login, REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.

from django.views.generic import ListView, DetailView

from TestingService.forms import RegistrationForm
from TestingService.models import Poll, Question, Answer, StudentAnswer, MyUser


class PermissionForStudents(PermissionRequiredMixin):

    def has_permission(self):
        return not self.request.user.is_teacher


class PermissionForTeachers(PermissionRequiredMixin):

    def has_permission(self):
        return self.request.user.is_teacher


class ListPolls(LoginRequiredMixin, PermissionForStudents, ListView):
    """Отображение списка тестов для студента"""
    template_name = 'index.html'
    context_object_name = 'list_polls'
    login_url = 'LoginViewAnonUser'
    model = Poll


class ListQuestions(LoginRequiredMixin, PermissionForStudents, DetailView):
    """ Отображение списка вопросов для студента"""
    template_name = 'detail.html'
    login_url = 'LoginViewAnonUser'
    model = Poll


class ListAnswers(LoginRequiredMixin, PermissionForStudents, DetailView):
    """Тест с вариантами ответов для студента"""
    template_name = 'detail_answers.html'
    model = Question
    login_url = 'LoginViewAnonUser'

    def post(self, request, *args, **kwargs):
        selected_answer = request.POST.get('ans', )
        if selected_answer:
            if not StudentAnswer.objects.filter(student=request.user, answer__question=self.get_object()).exists():
                otvet = StudentAnswer.objects.create(answer=Answer.objects.get(answer_text=selected_answer,
                                                                               question=self.get_object()),
                                                     student=request.user,
                                                     votes=0)
                otvet.save()
                if otvet.answer.is_correct:
                    otvet.votes = 1
                    otvet.save()
                    self.extra_context = {'message': 'Ваш ответ принят, перейдите обратно к списку вопросов, чтобы '
                                                     'выбрать '
                                                     'следующий'}
                    return self.get(request, *args, **kwargs)
                self.extra_context = {'message': 'Ваш ответ принят, перейдите обратно к списку вопросов, чтобы выбрать '
                                                 'следующий'}
                return self.get(request, *args, **kwargs)
            self.extra_context = {'message': 'Вы уже ответили на этот вопрос выберите другой'}
            return self.get(request, *args, **kwargs)
        self.extra_context = {'message': 'Выберите один из вариантов'}
        return self.get(request, *args, **kwargs)


class ResultPollsStudent(LoginRequiredMixin, PermissionForStudents, ListView):
    """Результаты пройденных тестов для конкретного студента, отображается статистика только для самого себя"""
    template_name = 'studentsresult.html'
    login_url = 'LoginViewAnonUser'

    def get_queryset(self):
        obj = Answer.objects.filter(studentanswer__student=self.request.user)
        if obj:
            return obj
        self.extra_context = {'message': 'Вы не прошли ни одного теста'}
        return self.get

    def get_context_data(self, **kwargs):
        context = super(ResultPollsStudent, self).get_context_data(**kwargs)
        context['answers'] = self.get_queryset()
        context['tests'] = set(Poll.objects.filter(question__answer__studentanswer__student=self.request.user))
        context['voprosi'] = Question.objects.filter(answer__studentanswer__student=self.request.user)
        context['test_point'] = {}
        for test in context['tests']:
            context['test_point'][test] = StudentAnswer.objects.filter(votes=1,
                                                                       student=self.request.user,
                                                                       answer__question__poll=test).count()
        context['all_answers_for_student_question'] = Answer.objects.filter()
        return context


def registration_user(request):
    """Регистрация новых пользователей"""
    if not request.user.is_authenticated:
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                is_teacher = form.cleaned_data.get('is_teacher')
                new_user = MyUser.objects.create_user(username=username, password=password, is_teacher=is_teacher)
                if not new_user.is_teacher:
                    authenticate(new_user)
                    login(request, new_user)
                    return redirect('ListPolls')
                authenticate(new_user)
                login(request, new_user)
                return redirect('ListStudent')
            message = form.errors
            form = RegistrationForm()
            return render(request, 'registration.html', {'message': message, 'form': form})
        form = RegistrationForm()
        return render(request, 'registration.html', {'form': form})
    raise PermissionDenied


class LoginViewAnonUser(LoginView, LoginRequiredMixin):
    """Авторизация пользователей"""
    form_class = AuthenticationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        is_teacher = form.user_cache.is_teacher
        if is_teacher:
            login(self.request, form.get_user())
            return HttpResponseRedirect('/studentpolls/')
        login(self.request, form.get_user())
        return HttpResponseRedirect('/')


class ListStudent(LoginRequiredMixin, PermissionForTeachers, ListView):
    """Просмотр результатов студентов для учителя"""
    template_name = 'result_for_teacher.html'
    queryset = MyUser.objects.filter(is_teacher=False)
    context_object_name = 'all_students'


class DetailStudentPollsResult(LoginRequiredMixin, PermissionForTeachers, DetailView):
    template_name = 'everypollresultforstudent.html'
    model = MyUser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        polls = set(Poll.objects.filter(question__answer__studentanswer__student=self.object))
        context['polls'] = {}
        for poll in polls:
            context['polls'][poll] = StudentAnswer.objects.filter(answer__question__poll=poll,
                                                                  student=self.object,
                                                                  answer__is_correct=True).count()

        return context


def teacher_required(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    """
    Decorator for views that checks that the user is logged in, redirecting
    to the log-in page if necessary.
    """
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated and u.is_teacher,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function)
    return actual_decorator


@teacher_required
def result_student_poll(request, pk_1, pk_2):
    """Просмотр результатов студента (кол-во баллов, правильные и неправильные ответы, вопросы)"""
    poll = get_object_or_404(Poll, pk=pk_1)
    stud = get_object_or_404(MyUser, pk=pk_2)
    questions = Question.objects.filter(poll=poll, answer__studentanswer__student=stud)
    student_answer = StudentAnswer.objects.filter(answer__question__poll=poll, student=stud)
    correct_answers = Answer.objects.filter(is_correct=True, question__poll=poll, studentanswer__student=stud)
    if request.method == 'POST':
        StudentAnswer.objects.filter(answer__question__poll=poll, student=stud).delete()
    return render(request, 'detail_polls_result_with_answers.html', {'poll': poll,
                                                                     'stud': stud,
                                                                     'questions': questions,
                                                                     'student_answer': student_answer,
                                                                     'correct_answers': correct_answers,
                                                                     })

TestingService/templates/anonymous_user.html
{% extends 'index.html' %}

{%  block middle %}
    <h1>{{ message }}</h1>
{% endblock %}

TestingService/templates/daily_report_for_admin.html
{% extends 'index.html' %}

{% block middle %}
    <h2>Тесты пройденные студентами сегодня:</h2>
    {% for poll in obj %}
    <br>{{ poll }}
    {% endfor %}



{% endblock %}

TestingService/templates/detail.html
{% extends 'index.html' %}
{% block middle %}
     <h1>Test {{ poll }}</h1>
    {% for quest in poll.question_set.all %}
        <p><a href="/question/{{ quest.id }}">{{ quest }}</a></p>
    {% endfor %}
    <p><a href="/result">Твоя статистика</a></p>
{% endblock %}

TestingService/templates/detail_answers.html
{% extends 'index.html' %}

{% block middle %}
    <h1>Test {{ question.poll }}</h1>
    <form method="post">
        {% csrf_token %}
        <h2>{{ question }}</h2>
        <p>{{ message }}</p>
        {% for ans in question.answer_set.all %}
            <input type="radio" name="ans" id="ans{{ forloop.counter }}" value="{{ ans }}"/>
            <label for="ans{{ forloop.counter }}">{{ ans }}</label><br><br>
        {% endfor %}
        <input type="submit" value="answer the question">
    </form>
    <p><a href="/{{question.poll.id }}">Назад к списку вопросов</a></p>
    <p><a href="/result">Твоя статистика</a></p>
{% endblock %}

TestingService/templates/detail_polls_result_with_answers.html
{% extends 'index.html' %}
{% block  middle  %}
    <h2>Тест "{{ poll }}"&emsp;Студент:&emsp;{{ stud }}&emsp;Балл:{{ correct_answers.count }}</h2>
    {% for question in questions %}
        {% for answer in student_answer %}
            {% if answer.answer.question == question %}
                <p>{{ question }}</p>&emsp;<i>Ответ студента:</i>&emsp;{{ answer }}&emsp;
                <i>Правильный ответ:&emsp;</i>
                {% for correct in question.answer_set.all %}
                    {% if correct.is_correct %}
                        {{ correct }}
                    {% endif %}
                {% endfor %}
            {% endif %}
            {% endfor %}
    {% endfor %}
    <form method="post">
    {% csrf_token %}
    <br><button type="submit">Сбросить результаты теста</button>
    </form>
{% endblock %}

TestingService/templates/everypollresultforstudent.html
{% extends 'index.html' %}

{%  block middle %}
    {% if not polls  %}<h2>Студент не прошел ни одного теста</h2>{% endif %}
    {% for poll, point in polls.items %}
        <p><a href="/studentpolls/users/{{ object.id }}/poll/{{ poll.id }}">{{ poll }}</a>
            &emsp;{{ point }}/{{ poll.question_set.all.count }}</p>
    {% endfor %}


{% endblock %}

TestingService/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block middle %}
    <h1>All tests</h1>
    <p>{{ message }}</p>
    {% for poll in list_polls %}
        <p><a href="{{ poll.id }}">{{ poll.name }}</a></p>
    {% endfor %}
    <p><a href="/result">Твоя статистика</a></p>
{% endblock %}
</body>
</html>

TestingService/templates/index_for_teacher.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block middle %}
    <h1>Students result</h1>
    <p>{{ message }}</p>
    {% for user in users %}
        <p><a href="{% url 'ListPolls' %}">{{ user }}</a></p>
    {% endfor %}
{% endblock %}
</body>
</html>

TestingService/templates/login.html
{% extends 'index.html' %}
{% block middle %}
    <h2 align="center">Авторизация</h2>
    <p>{{ message }}</p>
    <form method="post">
    {% csrf_token %}
        <p>{{form.as_p }}</p>
    <button type="submit">Авторизоваться</button>
    </form>
<p><a href="{% url 'registration_user' %}">Регистрация</a></p>


{% endblock %}

TestingService/templates/month_report_for_teachers.html
{% extends 'index.html' %}

{% block middle %}
    <h2>За месяц студенты прошли {{ obj }} тестов </h2>




{% endblock %}

TestingService/templates/registration.html
{% extends 'index.html' %}
{% block middle %}
    <h2 align="center">Регистрация</h2>
    <p>{{ message }}</p>
    <form method="post">
    {% csrf_token %}
        <p>{{ form.username.label }}&emsp;{{ form.username }}</p>
        <p>{{ form.password1.label }}&emsp;{{ form.password1 }}</p>
        <p>{{ form.password2.label }}&emsp;{{ form.password2 }}</p>
        <p>{{ form.is_teacher.label }}&emsp;{{ form.is_teacher }}</p>
    <button type="submit">Зарегистрироваться</button>
    </form>
<p><a href="{% url 'LoginViewAnonUser' %}">Авторизация</a></p>


{% endblock %}

TestingService/templates/registration_1.html
{% extends 'index.html' %}
{% block middle %}
    <h2 align="center">Пожалуйста введите Email</h2>
    <p>{{ message }}</p>
    <form method="post">
    {% csrf_token %}
        <p>{{ form.email.label }}&emsp;{{ form.email }}</p>
    <button type="submit">Зарегистрироваться</button>
    </form>
<p><a href="{% url 'LoginViewAnonUser' %}">Авторизация</a></p>


{% endblock %}

TestingService/templates/result_for_teacher.html
{% extends 'index.html' %}
{% block middle %}
    <h1>Результаты студента</h1>
    {% for student in all_students %}
        <p><a href="/studentpolls/users/{{ student.id }}">{{ student}}</a></p>
    {% endfor %}
{% endblock %}

TestingService/templates/studentsresult.html
{% extends 'index.html' %}
{% block middle %}
    {{ message }}
    {% for i, c in test_point.items %}                                                {# dict "Название теста" : балл студента, чтобы было проще отобразить #}
        <h2>Тест&ensp;"{{ i }}"&emsp;<i style="color: brown">Ваш балл:{{ c }}</i></h2>
        {% for j in voprosi %}
            {% if j.poll == i %}
            <p>{{ j }}&emsp;<br>Ваш ответ:
                {% for m in answers %}                                          {# Получение ответов студента #}
                    {% if m.question == j %}&emsp;"{{ m }}"
                    {% endif %}
                {% endfor %}

                {% for right in all_answers_for_student_question %}             {# Получение правильных ответов #}
                            {% if right.question == j and right.is_correct %}
                                Правильный ответ:&emsp;"{{ right }}"
                            {% endif %}
                        {% endfor %}
            </p>
            {% endif %}
        {% endfor %}
    {% endfor %}
{% endblock %}